version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
    # group official actions into a single PR, unless it's a major version bump
    groups:
      github-actions:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
